### ISSUE TITLE
more control over install timeout

### ISSUE THREAD

**Issue by rfk** [mozilla-services/mopytools#5]
Filing this from an IRC dump, as a reminder for me to follow it up when I'm not travelling...

<rasher> rfkelly: It looks like there's a 5 minute timeout on running the pip install for dependencies. My hardware can't manage that
<rfkelly> rasher: oh, interesting, I did not know this - how did you increase it?
<rasher> ran this in a loop on another terminal :) - sed -i 's/300/3600/' lib/python2.6/site-packages/mopytools/util.py 
<rasher> not ideal, but it did the trick
<rfkelly> yikes
<rasher> It looks like there's a --timeout argument to util.py, but I wasn't sure where to put it

**Comment by rasher** [comment]
It would have been helpful to be able to configure this using a environment variable (since I'm not invoking the util directly). Additionally, a more descriptive error message than "Timed out!" would have helped diagnose the problem. In particular, that this isn't necessarily a network timeout, but could be caused by slow compile times or similar. Information in the error message about how to increase the timeout would also be nice.

**Comment by rfk** [comment]
We don't plan any furthe work on MoPyTools and new projects are not using it; closing this out as WONTFIX.
